/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  corePlugins: {
    preflight: true,
  },
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#f2b6cb",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb1c5",
        "on-secondary-container": "#7b4c5e",
        "on-tertiary-fixed": "#25181e",
        "inverse-on-surface": "#f2f0f0",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#36282e",
        "on-primary": "#ffffff",
        "secondary-container": "#fec1d6",
        "on-primary-fixed": "#3f001b",
        "surface-tint": "#ab2c5d",
        "on-tertiary-fixed-variant": "#524249",
        "surface-container-highest": "#e4e2e2",
        "outline-variant": "#ddbfc5",
        "tertiary-fixed-dim": "#d7c1c8",
        "on-error-container": "#93000a",
        "outline": "#8a7176",
        "surface-bright": "#fbf9f8",
        "tertiary-container": "#a28e95",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#f4dce4",
        "on-primary-container": "#5e002b",
        "surface": "#fbf9f8",
        "on-primary-fixed-variant": "#8b0e45",
        "primary-container": "#f06292",
        "surface-variant": "#e4e2e2",
        "surface-dim": "#dbd9d9",
        "on-secondary-fixed": "#330f1f",
        "on-secondary-fixed-variant": "#65394b",
        "on-surface-variant": "#574146",
        "inverse-surface": "#303030",
        "primary": "#ab2c5d",
        "surface-container": "#efeded",
        "primary-fixed": "#ffd9e1",
        "surface-container-high": "#eae8e7",
        "tertiary": "#6b5a60",
        "error": "#ba1a1a",
        "background": "#fbf9f8",
        "secondary": "#805062",
        "surface-container-low": "#f5f3f3",
        "on-surface": "#1b1c1c",
        "secondary-fixed": "#ffd9e4",
        "error-container": "#ffdad6",
        "on-background": "#1b1c1c",
        "inverse-primary": "#ffb1c5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.0rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "12px",
        "container-padding": "24px",
        "gutter": "16px",
        "stack-sm": "4px",
        "stack-lg": "24px",
        "base": "8px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "48px",
        "container-margin": "16px",
        "container-margin-md": "24px",
        "container-margin-lg": "40px",
        "container-margin-xl": "64px",
        "navbar-height": "64px"
      },
      fontFamily: {
        "sans": ["Inter", "Poppins", "sans-serif"],
        "display": ["Inter", "Montserrat", "sans-serif"],
        "body": ["Inter", "Poppins", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "title-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "data-tabular": ["14px", { "lineHeight": "20px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
};
