/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  corePlugins: {
    preflight: true,
  },
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-secondary-container": "#006776",
        "on-primary-container": "#ffece9",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f4f5",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#93000d",
        "tertiary": "#00588f",
        "on-tertiary-container": "#e7f0ff",
        "surface-dim": "#d9dadb",
        "outline-variant": "#e6bdb8",
        "on-tertiary-fixed-variant": "#004a79",
        "inverse-primary": "#ffb4ab",
        "primary": "#2563EB",
        "tertiary-fixed-dim": "#9acbff",
        "on-surface-variant": "#5d3f3c",
        "tertiary-fixed": "#d0e4ff",
        "surface-tint": "#2563EB",
        "on-primary-fixed": "#001a41",
        "primary-fixed-dim": "#a2c1ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#62d6ed",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed": "#d0e4ff",
        "error": "#ba1a1a",
        "on-background": "#191c1d",
        "on-secondary-fixed-variant": "#004e5a",
        "surface-bright": "#f8f9fa",
        "on-primary": "#ffffff",
        "background": "#f8f9fa",
        "secondary": "#1E3A8A",
        "outline": "#926f6b",
        "surface-container": "#edeeef",
        "on-error": "#ffffff",
        "secondary-fixed": "#a4eeff",
        "on-surface": "#191c1d",
        "on-secondary-fixed": "#001f25",
        "inverse-on-surface": "#f0f1f2",
        "surface": "#f8f9fa",
        "primary-container": "#2563EB",
        "inverse-surface": "#2e3132",
        "surface-container-high": "#e7e8e9",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "tertiary-container": "#0071b6",
        "on-tertiary-fixed": "#001d34",
        "secondary-container": "#75e7fe"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.0rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "base": "4px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "48px",
        "gutter": "16px",
        "container-margin": "16px",
        "container-margin-md": "24px",
        "container-margin-lg": "40px",
        "container-margin-xl": "64px",
        "navbar-height": "64px"
      },
      fontFamily: {
        "sans": ["Poppins", "sans-serif"],
        "display": ["Montserrat", "sans-serif"],
        "body": ["Poppins", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "title-lg": ["Montserrat", "sans-serif"],
        "label-md": ["Poppins", "sans-serif"],
        "body-md": ["Poppins", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "data-tabular": ["Poppins", "sans-serif"],
        "body-sm": ["Poppins", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "title-lg": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "data-tabular": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
};
