FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY proto ./proto
COPY pkg ./pkg
COPY services/activity-service ./services/activity-service

WORKDIR /app/services/activity-service

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o activity-service ./cmd

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata
ENV TZ=Asia/Jakarta

WORKDIR /app

COPY --from=builder /app/services/activity-service/activity-service .

EXPOSE 50053

CMD ["./activity-service"]
