services:

  # ==============================
  # MIGRATIONS (POSTGRESQL PUSAT)
  # ==============================
  auth-migrate:
    image: migrate/migrate
    container_name: lopiq-auth-migrate
    volumes:
      - ./services/auth-service/migrations:/migrations
    command: ["-path=/migrations", "-database=postgres://user_lopiq_auth:lopiqauthPassword%402k26%23@postgres_apps:5432/db_lopiq_auth?sslmode=disable", "up"]
    restart: on-failure
    networks:
      - lopiq-network
      - app-global-net

  user-migrate:
    image: migrate/migrate
    container_name: lopiq-user-migrate
    volumes:
      - ./services/user-service/migrations:/migrations
    command: ["-path=/migrations", "-database=postgres://user_lopiq_user:lopiquserPassword%402k26%23@postgres_apps:5432/db_lopiq_user?sslmode=disable", "up"]
    restart: on-failure
    networks:
      - lopiq-network
      - app-global-net

  # ==============================
  # GOLANG MICROSERVICES
  # ==============================
  auth-service:
    build:
      context: .
      dockerfile: deployments/docker/auth-service/Dockerfile
    container_name: lopiq-auth-service
    depends_on:
      - auth-migrate
    ports:
      - "50051:50051"
    env_file:
      - ./services/auth-service/.env
    environment:
      - PORT=50051
      - JWT_SECRET=lopiq_super_secret_jwt_key_2026
      - DB_TYPE=postgres
      - DB_HOST=postgres_apps
      - DB_PORT=5432
      - DB_USER=user_lopiq_auth
      - DB_PASSWORD=lopiqauthPassword@2k26#
      - DB_NAME=db_lopiq_auth
      - DB_SSLMODE=disable
    restart: unless-stopped
    networks:
      - lopiq-network
      - app-global-net

  user-service:
    build:
      context: .
      dockerfile: deployments/docker/user-service/Dockerfile
    container_name: lopiq-user-service
    depends_on:
      - user-migrate
    ports:
      - "50052:50052"
    env_file:
      - ./services/user-service/.env
    environment:
      - PORT=50052
      - DB_TYPE=postgres
      - DB_HOST=postgres_apps
      - DB_PORT=5432
      - DB_USER=user_lopiq_user
      - DB_PASSWORD=lopiquserPassword@2k26#
      - DB_NAME=db_lopiq_user
      - DB_SSLMODE=disable
    restart: unless-stopped
    networks:
      - lopiq-network
      - app-global-net

  activity-migrate:
    image: migrate/migrate
    container_name: lopiq-activity-migrate
    volumes:
      - ./services/activity-service/migrations:/migrations
    command: ["-path=/migrations", "-database=postgres://user_lopiq_activity:lopiqactivityPassword%402k26%23@postgres_apps:5432/db_lopiq_activity?sslmode=disable", "up"]
    restart: on-failure
    networks:
      - lopiq-network
      - app-global-net

  activity-service:
    build:
      context: .
      dockerfile: deployments/docker/activity-service/Dockerfile
    container_name: lopiq-activity-service
    depends_on:
      - activity-migrate
    ports:
      - "50053:50053"
    env_file:
      - ./services/activity-service/.env
    environment:
      - PORT=50053
      - DB_TYPE=postgres
      - DB_HOST=postgres_apps
      - DB_PORT=5432
      - DB_USER=user_lopiq_activity
      - DB_PASSWORD=lopiqactivityPassword@2k26#
      - DB_NAME=db_lopiq_activity
      - DB_SSLMODE=disable
    restart: unless-stopped
    networks:
      - lopiq-network
      - app-global-net

  # ==============================
  # REST API GATEWAY
  # ==============================
  api-gateway:
    build:
      context: .
      dockerfile: deployments/docker/api-gateway/Dockerfile
    container_name: lopiq-api-gateway
    depends_on:
      - auth-service
      - user-service
      - activity-service
    ports:
      - "5000:5000"
    env_file:
      - ./services/api-gateway/.env
    environment:
      - PORT=5000
      - JWT_SECRET=lopiq_super_secret_jwt_key_2026
      - AUTH_SERVICE_ADDR=lopiq-auth-service:50051
      - USER_SERVICE_ADDR=lopiq-user-service:50052
      - ACTIVITY_SERVICE_ADDR=lopiq-activity-service:50053
    restart: unless-stopped
    networks:
      - lopiq-network
      - app-global-net


  # ==============================
  # FRONTEND (VUE SPA)
  # ==============================
  frontend:
    build:
      context: .
      dockerfile: deployments/docker/web/Dockerfile
    container_name: lopiq-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - lopiq-network
      - app-global-net

networks:
  lopiq-network:
    driver: bridge
  app-global-net:
    external: true
