ALTER TABLE users 
ADD COLUMN IF NOT EXISTS institusi VARCHAR(255),
ADD COLUMN IF NOT EXISTS jurusan VARCHAR(255),
ADD COLUMN IF NOT EXISTS pembimbing VARCHAR(255),
ADD COLUMN IF NOT EXISTS periode_mulai DATE,
ADD COLUMN IF NOT EXISTS periode_selesai DATE,
ADD COLUMN IF NOT EXISTS status_magang VARCHAR(50) DEFAULT 'aktif';
