FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY proto ./proto
COPY pkg ./pkg
COPY services/api-gateway ./services/api-gateway

WORKDIR /app/services/api-gateway
RUN go mod download
RUN go build -ldflags="-s -w" -o api-gateway ./cmd/main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates tzdata
ENV TZ=Asia/Makassar

WORKDIR /app

COPY --from=builder /app/services/api-gateway/api-gateway .

EXPOSE 5000

CMD ["./api-gateway"]
