FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY proto ./proto
COPY pkg ./pkg
COPY services/attendance-service ./services/attendance-service

WORKDIR /app/services/attendance-service

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o attendance-service ./cmd

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata
ENV TZ=Asia/Jakarta

WORKDIR /app

COPY --from=builder /app/services/attendance-service/attendance-service .

EXPOSE 50055

CMD ["./attendance-service"]
