FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY proto ./proto
COPY pkg ./pkg
COPY services/user-service ./services/user-service

WORKDIR /app/services/user-service

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o user-service ./cmd

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata
ENV TZ=Asia/Jakarta

WORKDIR /app

COPY --from=builder /app/services/user-service/user-service .

EXPOSE 50052

CMD ["./user-service"]
